application: pieldecafeapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: views/stylesheets
- url: /javascripts
  static_dir: views/javascripts
- url: /.*
  script: main.app
  login: required
  secure: always

libraries:
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?.*\.pyc
- ^(.*/)?\.git
- ^(.*/)?\.gitignore
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.coffee$
